### ISSUE TITLE
Name is empty

### ISSUE THREAD

**Issue by guyluz11** [janstol/yeedart#10]
The device from Yeelight.discover() return with an empty name `''` although the name appears in the Yeelight app.

Device type: yeelight 1SE

Other params seem correct.

**Comment by janstol** [comment]
Hi, this happens because name reported in discover response is stored on device and name shown in the Yeelight is stored in cloud. See the [documentation](https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf).

![set_name_prop](https://user-images.githubusercontent.com/7049545/135056508-05429865-8437-428a-b3e2-960eccbfd5c5.png)

So I think you should probably set the name by calling `device.setName` method.
